-- Create the table
CREATE TABLE university_professors (
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    university VARCHAR(255),
    university_shortname VARCHAR(255),
    university_city VARCHAR(255),
    function TEXT,
    organization VARCHAR(255),
    organization_sector VARCHAR(255)
);

-- Insert the data
INSERT INTO university_professors (firstname, lastname, university, university_shortname, university_city, function, organization, organization_sector) VALUES
('Karl', 'Aberer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Chairman of L3S Advisory Board', 'L3S Advisory Board', 'Education & research'),
('Karl', 'Aberer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Member Conseil of Zeno-Karl Schindler Foundation', 'Zeno-Karl Schindler Foundation', 'Education & research'),
('Karl', 'Aberer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Member of Conseil Fondation IDIAP', 'Fondation IDIAP', 'Education & research'),
('Karl', 'Aberer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Panel Member', 'SNF Ambizione Program', 'Education & research'),
('Reza Shokrollah', 'Abhari', 'ETH Zürich', 'ETH', 'Zurich', 'Aufsichtsratsmandat', 'PNE Wind AG', 'Energy, environment & mobility'),
('Georges', 'Abou Jaoudé', 'ETH Lausanne', 'EPF', 'Lausanne', 'Professeur invité (2 interventions d''une semaine)', 'Kazan Federal University, Russia', 'Education & research'),
('Hugues', 'Abriel', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Cloetta Stiftung', 'Education & research'),
('Daniel', 'Aebersold', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Berner Radium-Stiftung', 'Pharma & health'),
('Daniel', 'Aebersold', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Janser Krebs-Stiftung', 'Pharma & health'),
('Daniel', 'Aebersold', 'Uni Bern', 'UBE', 'Bern', 'NA', 'SWAN Isotopen AG', 'Technology'),
('Christoph', 'Aebi', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Bernische Stiftung für krebskranke Kinder und Jugendliche', 'Pharma & health'),
('Christoph', 'Aebi', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Ronald McDonald Stiftung', 'Society, Social, Culture & Sports'),
('Marcelo', 'Aebi', 'Uni Lausanne', 'ULA', 'Lausanne', 'NA', 'Activités académiques', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Beirat', 'Singapore International Advisory Committee for Biomedical Sciences', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Chairman, Beirat', 'Advisory Board Novartis Venture Fund', 'Financial industry & insurances'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Founder & Chairman of the BOD', 'Amazentis', 'Technology'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'NA', 'Fondation Claude Nobs', 'Society, Social, Culture & Sports'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'NA', 'Fondation Terre des Hommes', 'Politics, administration, justice system & security sector'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'NA', 'Italian Institute of Technology', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'NA', 'Singapore Biomedical Sciences International', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'NA', 'World Economic Forum', 'Commerce, trade & services'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Part of the presidential duties', 'CSEM', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Part of the presidential duties', 'Fondation Brocher', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Part of the presidential duties', 'Fondation Campus Biotech Geneva', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Part of the presidential duties', 'Fondation Claude Verdan', 'Society, Social, Culture & Sports'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Part of the presidential duties', 'Fondation EPFL+', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Part of the presidential duties', 'Fondation les Bois Chamblard', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Part of the presidential duties', 'Fondation pour l''étude des eaux du Léman', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Part of the presidential duties', 'Fondation pour la formation continue lausannoise', 'Education & research'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Verwaltungsrat', 'Lonza Group', 'Technology'),
('Patrick', 'Aebischer', 'ETH Lausanne', 'EPF', 'Lausanne', 'Verwaltungsrat', 'Nestlé', 'Industry, construction & agriculture'),
('Stephan', 'Aier', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Beratung und Veranstaltungen im Bereich Enterprise Architecture Management', 'TWZ GmbH', 'Not classifiable'),
('Stephan', 'Aier', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Lehrauftrag Enterprise Architecture', 'Reykjavik University', 'Education & research'),
('Anastasia', 'Ailamaki', 'ETH Lausanne', 'EPF', 'Lausanne', 'Consulting on data mgmt', 'S2P Lion, Germany', 'Not classifiable'),
('Cesla', 'Amarelle', 'Uni Neuenburg', 'UNE', 'Neuchâtel', 'Mandat', 'Nationalrat', 'Politics, administration, justice system & security sector'),
('Manuel', 'Ammann', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Verwaltungsrat', 'Neue Bank AG', 'Financial industry & insurances'),
('Manuel', 'Ammann', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Verwaltungsrat', 'St. Galler Kantonalbank AG', 'Financial industry & insurances'),
('Manuel', 'Ammann', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Verwaltungsratspräsident', 'Algofin AG', 'Consulting, public relations, legal & trust'),
('Christophe', 'Ancey', 'ETH Lausanne', 'EPF', 'Lausanne', 'Prise en compte du risque de reptation sur la télécabine du Lys, pylônes P9-11', 'Espace Cauterets, Mairie, Cauterets', 'Politics, administration, justice system & security sector'),
('Marilyne', 'Andersen', 'ETH Lausanne', 'EPF', 'Lausanne', 'Board member', 'ECOVEST SA', 'Commerce, trade & services'),
('Marilyne', 'Andersen', 'ETH Lausanne', 'EPF', 'Lausanne', 'Member of Industry Agenda Council for Real Estate and Urbanization', 'World Economic Forum', 'Commerce, trade & services'),
('Jean-Marie', 'Annoni', 'Uni Freiburg', 'UFR', 'Fribourg', 'Neurologe', 'Freiburger Spital', 'Pharma & health'),
('John', 'Antonakis', 'Uni Lausanne', 'ULA', 'Lausanne', 'NA', 'Activités académiques', 'Education & research'),
('Omid', 'Aschari', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Mitglied', 'Nationaler Geistiger Rat der Bahá''í der Schweiz', 'Society, Social, Culture & Sports'),
('Omid', 'Aschari', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Verwaltungsratspräsident und Gründer', 'ASG Strategy Group AG', 'Consulting, public relations, legal & trust'),
('David Atienza', 'Alonso', 'ETH Lausanne', 'EPF', 'Lausanne', 'Consultancy on embedded systems uses for swallowing and chewing monitoring', 'Nestec SA', 'Industry, construction & agriculture'),
('Jean-Jacques', 'Aubert', 'Uni Neuenburg', 'UNE', 'Neuchâtel', 'Député', 'Grand Conseil NE', 'Politics, administration, justice system & security sector'),
('Jean-Jacques', 'Aubert', 'Uni Neuenburg', 'UNE', 'Neuchâtel', 'Vice-président', 'Académie suisse des sciences humaines et sociales', 'Society, Social, Culture & Sports'),
('Drahomir', 'Aujesky', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Schweizerische Gesellschaft für allgemeine innere Medizin', 'Pharma & health'),
('Johan', 'Auwerx', 'ETH Lausanne', 'EPF', 'Lausanne', 'Biomedical consulting - Founder and BOD (Director - approved by EPFL)', 'Reamol Biomedical Consultung, Buchillon, CH', 'Consulting, public relations, legal & trust'),
('Johan', 'Auwerx', 'ETH Lausanne', 'EPF', 'Lausanne', 'Mitochondrial metabolism and deseases - Founder & SAB member', 'Mitobridge, Cambridge, MA, USA', 'Technology'),
('Johan', 'Auwerx', 'ETH Lausanne', 'EPF', 'Lausanne', 'NAD metabolism - SAB member', 'Metro Mid-Atalantic Biotech, Birmingham, MI, USA', 'Technology'),
('Johan', 'Auwerx', 'ETH Lausanne', 'EPF', 'Lausanne', 'Nutraceuticals - SAB member', 'Amazentis, Ecublens, Switzerland', 'Technology'),
('Johan', 'Auwerx', 'ETH Lausanne', 'EPF', 'Lausanne', 'Nutrition & Phytochemistry - Founder & Consultant', 'PhytoDia, Illkirch, France', 'Pharma & health'),
('François', 'Avellan', 'ETH Lausanne', 'EPF', 'Lausanne', 'Associé minoritaire dans la start-up d''un ancien doctorant', 'Power Vision Engineering Sàrl, Ecublens', 'Industry, construction & agriculture'),
('François', 'Avellan', 'ETH Lausanne', 'EPF', 'Lausanne', 'Expertise du rendement des turbines de la centrale de La Higuera, Chili, dans le cadre d''une procédure juridique', 'Barros, Letelier & Gonzalez Attorneys at Law, Chile', 'Consulting, public relations, legal & trust'),
('Kay Werner', 'Axhausen', 'ETH Zürich', 'ETH', 'Zurich', 'VR-Mandat der Spin-Off-Firma', 'Senozon (Schweiz) AG', 'Consulting, public relations, legal & trust'),
('Philippe', 'Bacchetta', 'Uni Lausanne', 'ULA', 'Lausanne', 'NA', 'Activités académiques', 'Education & research'),
('Andrea', 'Back', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Beirätin', 'Crosswalk AG', 'Consulting, public relations, legal & trust'),
('Andrea', 'Back', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Beirätin, Beratung', 'CID GmbH', 'Technology'),
('Andrea', 'Back', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Gutachterin', 'Marie Heim-Vögtlin-Programm des Schweizerischen Nationalfonds, Abteilung Geistes- und Sozialwissenschaften', 'Education & research'),
('Andrea', 'Back', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Wissenschaftliche Beirätin', 'Leibniz-Informationszentrum Wirtschaft', 'Education & research'),
('Marco', 'Bakker', 'ETH Lausanne', 'EPF', 'Lausanne', 'CEO, Architect', 'Bakker & Blanc Architectes Lausanne, Zurich', 'Industry, construction & agriculture'),
('Artur', 'Baldauf', 'Uni Bern', 'UBE', 'Bern', 'NA', 'International School of Bern', 'Education & research'),
('Artur', 'Baldauf', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Securitas AG', 'Politics, administration, justice system & security sector'),
('Christophe', 'Ballif', 'ETH Lausanne', 'EPF', 'Lausanne', 'Chef de division CSEM PV-center, officiellement depuis 1.10.2012', 'CSEM, Neuchâtel', 'Education & research'),
('Christophe', 'Ballif', 'ETH Lausanne', 'EPF', 'Lausanne', 'Consultant technologique et membre du conseil d''administration', 'Asgalium Unitec SA, Cortaillod', 'Industry, construction & agriculture'),
('Christophe', 'Ballif', 'ETH Lausanne', 'EPF', 'Lausanne', 'Membre comité de conseil Active Niche Funds (fonds dédié au Solaire)', 'ANF SA, Lausanne', 'Financial industry & insurances'),
('Christophe', 'Ballif', 'ETH Lausanne', 'EPF', 'Lausanne', 'Panel, clean energy research program, Singapour', 'Economic development Board (EDB), Raffles Tower, Singapour', 'Commerce, trade & services'),
('Yann', 'Barrandon', 'Uni Lausanne', 'ULA', 'Lausanne', 'Conseil d''administration', 'gyMetrics SA, Ecublens', 'Technology'),
('Yann', 'Barrandon', 'Uni Lausanne', 'ULA', 'Lausanne', 'Consultant', 'A*Star IMB Biopolis, Singapour', 'Education & research'),
('David Andrew', 'Barry', 'ETH Lausanne', 'EPF', 'Lausanne', 'Co-Editor', 'Advances in Water Resources (Elsevier Journal)', 'Media & communication'),
('David Andrew', 'Barry', 'ETH Lausanne', 'EPF', 'Lausanne', 'Fellowships Committee', 'Royal Society of Edinburgh, UK', 'Education & research'),
('David Andrew', 'Barry', 'ETH Lausanne', 'EPF', 'Lausanne', 'Member and expert to the Sinergia section', 'Swiss National Science Foundation - Sinergia', 'Education & research'),
('David Andrew', 'Barry', 'ETH Lausanne', 'EPF', 'Lausanne', 'Member of the SNF Council', 'Swiss National Science Foundation', 'Education & research'),
('David Andrew', 'Barry', 'ETH Lausanne', 'EPF', 'Lausanne', 'Visiting Professor', 'University of Edinburgh, UK', 'Education & research'),
('Pius Eliseo', 'Baschera', 'ETH Zürich', 'ETH', 'Zurich', 'VP des Beirates', 'ARDEX GmbH', 'Industry, construction & agriculture'),
('Pius Eliseo', 'Baschera', 'ETH Zürich', 'ETH', 'Zurich', 'VP des Beirates', 'Vorwerk & Co. KG', 'Commerce, trade & services'),
('Pius Eliseo', 'Baschera', 'ETH Zürich', 'ETH', 'Zurich', 'VR-Mandat', 'Roche Holding AG', 'Pharma & health'),
('Pius Eliseo', 'Baschera', 'ETH Zürich', 'ETH', 'Zurich', 'VR-Mandat', 'Schindler Holding AG', 'Industry, construction & agriculture'),
('Pius Eliseo', 'Baschera', 'ETH Zürich', 'ETH', 'Zurich', 'VR-Präsidium', 'Hilti AG', 'Industry, construction & agriculture'),
('Pius Eliseo', 'Baschera', 'ETH Zürich', 'ETH', 'Zurich', 'VR-Präsidium', 'Venture Incubator AG', 'Financial industry & insurances'),
('David Alan', 'Basin', 'ETH Zürich', 'ETH', 'Zurich', 'Vorsitzender der Geschäftsführung', 'Contego Laboratories GmbH', 'Technology'),
('Claudio', 'Bassetti', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Fondazione Eccles', 'Education & research'),
('Claudio', 'Bassetti', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Fondazione Neuroscienze Ticino', 'Education & research'),
('Claudio', 'Bassetti', 'Uni Bern', 'UBE', 'Bern', 'NA', 'SITEM', 'Pharma & health'),
('Iris', 'Baumgartner', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Spital Thun AG', 'Pharma & health'),
('Iris', 'Baumgartner', 'Uni Bern', 'UBE', 'Bern', 'NA', 'Unitectra', 'Consulting, public relations, legal & trust'),
('Aurelio', 'Bay', 'ETH Lausanne', 'EPF', 'Lausanne', 'Présidence du Jury des examens du GYB', 'GYB Gymnase Intercantonal de la Broye, Payerne', 'Education & research'),
('Eva', 'Bayer Fluckiger', 'ETH Lausanne', 'EPF', 'Lausanne', 'Editrice en chef de la revue Commentarii Mathematici Helvetici', 'Société Mathématique Suisse', 'Education & research'),
('Eva', 'Bayer Fluckiger', 'ETH Lausanne', 'EPF', 'Lausanne', 'Membre', 'Stiftung zur Förderung der mathematischen Wissenschaften in der Schweiz', 'Education & research'),
('Eva', 'Bayer Fluckiger', 'ETH Lausanne', 'EPF', 'Lausanne', 'Membre du comité éditorial', 'Archiv der Mathematik', 'Media & communication'),
('Eva', 'Bayer Fluckiger', 'ETH Lausanne', 'EPF', 'Lausanne', 'Membre du comité éditorial', 'International Journal of Number Theory', 'Media & communication'),
('Eva', 'Bayer Fluckiger', 'ETH Lausanne', 'EPF', 'Lausanne', 'Membre du comité éditorial', 'Journal of Algebra', 'Media & communication'),
('Eva', 'Bayer Fluckiger', 'ETH Lausanne', 'EPF', 'Lausanne', 'Membre du conseil de la recherche Division II', 'FNS, Berne', 'Education & research'),
('Stefan', 'Bechtold', 'ETH Zürich', 'ETH', 'Zurich', 'NA', 'Fondation Professeur Walther Hug', 'Education & research'),
('Rolf', 'Becker', 'Uni Bern', 'UBE', 'Bern', 'NA', 'GESIS Leibniz Institut', 'Education & research'),
('Christian', 'Belz', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Verwaltungsrat', 'Création Baumann', 'Industry, construction & agriculture'),
('Christian', 'Belz', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Verwaltungsrat', 'Olma Messen St. Gallen', 'Industry, construction & agriculture'),
('Christian', 'Belz', 'Uni St. Gallen', 'USG', 'Saint Gallen', 'Verwaltungsrat', 'NA', 'Not classifiable');

